version: "3.9"
services:
  shop:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      TG_BOT_TOKEN: $TG_BOT_TOKEM
      OWNER_ID: $OWNER_ID
      AUTH_CHANNEL: $AUTH_CHANNEL
